# Generated by Django 4.1.7 on 2023-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0002_pet_birth_date_pet_breed_pet_color_pet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='uuid',
            field=models.CharField(default='5f18fc', max_length=7, unique=True),
        ),
    ]
