# Generated by Django 4.1.7 on 2023-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.CharField(default='01/01/23', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='uuid',
            field=models.CharField(default='e9b595', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='petprofilevisibility',
            name='field_name',
            field=models.CharField(choices=[('name', 'Name'), ('birth_date', 'Birth Date'), ('breed', 'Breed'), ('description', 'Description'), ('med_records', 'Medical Records'), ('profile_picture', 'Profile Picture'), ('address', 'address'), ('color', 'color')], max_length=50),
        ),
        migrations.AlterField(
            model_name='petprofilevisibility',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='petprofilevisibility',
            unique_together={('pet', 'field_name')},
        ),
    ]
