# Generated by Django 4.1.7 on 2023-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0003_pet_qr_code_alter_pet_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], default='dog', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_location',
            field=models.CharField(default='No informado', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone',
            field=models.CharField(default='+5491123456710', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='uuid',
            field=models.CharField(default='54123b', max_length=7, unique=True),
        ),
    ]
