# Generated by Django 4.1.7 on 2023-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0004_pet_species_pet_vet_location_alter_pet_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='uuid',
            field=models.CharField(default='6c7cfe', max_length=7, unique=True),
        ),
    ]
